### ISSUE TITLE
code-snippet.hbs no such file

### ISSUE THREAD

**Issue by lmcardle** [ef4/ember-code-snippet#10]
I have been using this addon to help document a large internal addon. Everything has been working however after a recent nombom I started having issues. When the server first starts up, ember s, the dummy app loads fine. However if I open ANY file (dummy app template, controller, addon component, etc) and save the file (even without making any changes...just open and click save), broccoli yells at me with the following error:

```
ENOENT: no such file or directory, stat '/.../tmp/broccoli_merge_trees-input_base_path-zfR4zjtM.tmp/1/dummy/templates/components/code-snippet.hbs'
```

In order to continue development and get around this issue, I have to restart my server on every file change. 

Any thoughts on how to track this issue down?

**Comment by jasonmit** [comment]
Also seeing this
