### ISSUE TITLE
Overriding `require` causes ember loader to throw warnings

### ISSUE THREAD

**Issue by runspired** [ef4/ember-code-snippet#17]
Example:

```cli
ember test
version: 2.3.0-beta.2
Built project successfully. Stored in "/Users/runspired/GitHub/flexi/tmp/class-tests_dist-TdmA0Cyi.tmp".
ok 1 PhantomJS 2.0 - JSCS - modules/flexi/components: modules/flexi/components/flexi-centered.js should pass jscs
    ---
        Log: |
            { type: 'warn',
              text: '\'unable to require.unsee, please upgrade loader.js to >= v3.3.0\'\n' }
    ...
```

I traced this down, and it appears a require override is inserted along with `highlight.js`, but examining the source shows it does not originate from `highlight.js` itself.  This addon passes highlight through `browserify`, I'm guessing browserify inserts the require.

**Comment by machty** [comment]
fwiw this also seems to cause issues with [ember-cli-blanket](https://github.com/sglanzer/ember-cli-blanket), which intercepts `require`.
