### ISSUE TITLE
Incompatible with `ember-cli-code-coverage>=0.3.6`

### ISSUE THREAD

**Issue by job13er** [ef4/ember-code-snippet#34]
I just wanted to bring it to your attention that the inclusion of `browserified-highligh.js` being generated [here](https://github.com/ef4/ember-code-snippet/blob/6825f77f95a3b1aa0409432721b49324f4b29e4d/index.js#L44-L48) and imported [here](https://github.com/ef4/ember-code-snippet/blob/6825f77f95a3b1aa0409432721b49324f4b29e4d/index.js#L52) is overwriting `window.require` and thus breaking `ember-cli-code-coverage` for anyone who is using both this addon and that one. 

See https://github.com/kategengler/ember-cli-code-coverage/issues/75 for a little more info.

**Comment by job13er** [comment]
Ah, looks like you (or at least some potential consumers of you) were already aware of this: https://github.com/ef4/ember-code-snippet/pull/23

Also looks like if the dependency issues w.r.t. #23 can be resolved, this will no longer be an issue.

**Comment by ming-codes** [comment]
Just found this as well, there's alternative package called `highlightjs` that's a webpack package. I don't think this one has the issue.

**Comment by ming-codes** [comment]
This may be fixed in the recent version. I see `ember-code-snippet` is now using a highlightjs in `vendor/`.

**Comment by ef4** [comment]
I'm pretty sure this is fixed in 2.0.0
