### ISSUE TITLE
Installing the addon throws an error

### ISSUE THREAD

**Issue by n1ru4l** [ef4/ember-code-snippet#35]
I just added this addon to my project by running `ember install ember-code-snippet`.
The install throws the following error:

```

Yarn: Installed ember-code-snippet
Cannot find module 'esprima'
Error: Cannot find module 'esprima'
```

By running `yarn add esprima` before `ember install ember-code-snippet` everything works fine.

This is related to `esprima` not being a direct dependency of the project. This could be solved by adding `esprima` to the list of dependencies.

**Comment by ef4** [comment]
I think this is not still an issue in 2.0.0.
