### ISSUE TITLE
Use within an addon?

### ISSUE THREAD

**Issue by sohara** [ef4/ember-code-snippet#4]
It doesn't appear as though this addon can be used within another addon. Is that expected? I'd like to use it within an addon but it appears that ember-code-snippet's `treeForApp` and `treeForVendor` hooks are never called, depsite it being a devDependency in the parent addon.

**Comment by ef4** [comment]
I think `devDependency` implies that it will only be needed when running your addon directly, from its standalone dummy app. Try making it a `dependency` instead.

**Comment by sohara** [comment]
Thanks @ef4. I move it to the dependencies property but now the `included` hook is blowing up with `Object #<Class> has no method 'import'`. Seems to be a known issue discussed here: https://github.com/ember-cli/ember-cli/issues/3718

**Comment by ef4** [comment]
Closing this because ember-cli now recommends using peerDependencies for recursive addon dependencies. 

https://github.com/ember-cli/ember-cli/issues/3718#issuecomment-166644137
