### ISSUE TITLE
Warnings on build

### ISSUE THREAD

**Issue by Gaurav0** [ef4/ember-code-snippet#52]
I get the following warnings while building:

[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: SnippetFinder
[API] Warning: Plugin uses .read/.rebuild API: SnippetFinder

**Comment by ef4** [comment]
I think this was fixed in 2.2.2 via https://github.com/ef4/ember-code-snippet/pull/51
